name: notes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter_svg: ^0.22.0
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.0
  intl: ^0.19.0
  flutter_tts: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pc.svg
    - assets/girl.png
    
  

  
